heat_template_version: 2015-04-30

description: >
  A template which starts openstack on AtomicOS.

parameters:
  AdminPassword:
    default: 'adminpass'
    description: The password for the keystone admin account, used for monitoring, querying neutron etc.
    type: string
    hidden: true
  AdminToken:
    default: 'asdf'
    description: The keystone auth secret.
    type: string
    hidden: true
  GlanceHost:
    type: string
    default: '127.0.0.1'
  GlancePort:
    default: "9292"
    description: Glance port.
    type: string
  KeystoneHost:
    type: string
    default: '127.0.0.1'
  MysqlRootPassword:
    type: string
    hidden: true
    default: '12345678'  # Has to be here because of the ignored empty value bug
  MysqlHost:
    type: string
    default: '127.0.0.1'
  NovaApiHost:
    type: string
    default: '127.0.0.1'  # Has to be here because of the ignored empty value bug
  NovaPassword:
    default: 'novapass'
    description: The password for the nova service account, used by nova-api.
    type: string
    hidden: true
  NovaPublicIP:
    type: string
    default: ''  # Has to be here because of the ignored empty value bug
  RabbitHost:
    type: string
    default: '127.0.0.1'  # Has to be here because of the ignored empty value bug
  RabbitPassword:
    default: guest
    description: The password for RabbitMQ
    type: string
    hidden: true
  RabbitUserName:
    default: guest
    description: The username for RabbitMQ
    type: string
  RabbitClientPort:
    default: 5672
    description: Set rabbit subscriber port, change this if using SSL
    type: number
  Hostname:
    type: string
    default: '' # Defaults to Heat created hostname
  ComputeDataDockerImage:
    default: kollaglue/centos-rdo-nova-compute-data:latest
    description: Data container image.
    type: string
  LibvirtDockerImage:
    default: kollaglue/centos-rdo-nova-libvirt:kilo
    description: Libvirt container image.
    type: string
  NovaNetworkDockerImage:
    default: kollaglue/centos-rdo-nova-network:kilo
    description: Nova Network container image.
    type: string
  NovaComputeDockerImage:
    default: kollaglue/centos-rdo-nova-compute:kilo
    description: Nova Compute container image.
    type: string

resources:
  BootConfig:
    type: Heat::InstallConfigAgent

  NovaCompute:
    type: OS::Nova::Server
    properties:
      user_data_format: SOFTWARE_CONFIG
      user_data: { get_attr: [BootConfig, config] }
      name: {get_param: Hostname}

  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }

  NovaComputeConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
        - name: ADMIN_TENANT_NAME
        - name: DB_ROOT_PASSWORD
        - name: FLAT_INTERFACE
        - name: GLANCE_API_SERVICE_HOST
        - name: GLANCE_API_SERVICE_PORT
        - name: HOST_IP
        - name: KEYSTONE_ADMIN_PASSWORD
        - name: KEYSTONE_ADMIN_SERVICE_HOST
        - name: KEYSTONE_ADMIN_SERVICE_PORT
        - name: KEYSTONE_ADMIN_TOKEN
        - name: KEYSTONE_AUTH_PROTOCOL
        - name: KEYSTONE_DB_PASSWORD
        - name: KEYSTONE_PUBLIC_SERVICE_HOST
        - name: MARIADB_ROOT_PASSWORD
        - name: MARIADB_SERVICE_HOST
        - name: METADATA_HOST
        - name: MYSQL_ROOT_PASSWORD
        - name: NETWORK_MANAGER
        - name: NOVA_API_SERVICE_HOST
        - name: NOVA_COMPUTE_SERVICE_HOST
        - name: NOVA_CONDUCTOR_SERVICE_HOST
        - name: NOVA_DB_NAME
        - name: NOVA_DB_PASSWORD
        - name: NOVA_DB_USER
        - name: NOVA_EC2_API_SERVICE_HOST
        - name: NOVA_EC2_COMPUTE_SERVICE_HOST
        - name: NOVA_EC2_NETWORK_SERVICE_HOST
        - name: NOVA_EC2_SERVICE_HOST
        - name: NOVA_KEYSTONE_PASSWORD
        - name: NOVA_KEYSTONE_USER
        - name: NOVA_NETWORK_SERVICE_HOST
        - name: PUBLIC_INTERFACE
        - name: PUBLIC_IP
        - name: RABBITMQ_SERVICE_HOST
      config: |
        #!/bin/bash
        env > /etc/openstack.env

  NovaComputeDeployment:
    type: OS::TripleO::SoftwareDeployment
    properties:
      config: {get_resource: NovaComputeConfig}
      server: {get_resource: NovaCompute}
      input_values:
        ADMIN_TENANT_NAME: admin
        DEBUG_LOGGING: false
        VERBOSE_LOGGING: true
        DB_ROOT_PASSWORD: {get_param: MysqlRootPassword}
        FLAT_INTERFACE: {get_param: NeutronPublicInterface}
        GLANCE_API_SERVICE_HOST: {get_param: GlanceHost}
        GLANCE_API_SERVICE_PORT: {get_param: GlancePort}
        HOST_IP: {get_attr: [NovaCompute, network, 0]}
        KEYSTONE_ADMIN_PASSWORD: {get_param: AdminPassword}
        KEYSTONE_ADMIN_SERVICE_HOST: {get_param: KeystoneHost}
        KEYSTONE_ADMIN_SERVICE_PORT: 35357
        KEYSTONE_ADMIN_TOKEN: {get_param: AdminToken}
        KEYSTONE_AUTH_PROTOCOL: http
        KEYSTONE_DB_PASSWORD: kolla
        KEYSTONE_PUBLIC_SERVICE_HOST: {get_param: KeystoneHost}
        MARIADB_ROOT_PASSWORD: {get_param: MysqlRootPassword}
        MARIADB_SERVICE_HOST: {get_param: MysqlHost}
        METADATA_HOST: {get_param: NovaApiHost}
        MYSQL_ROOT_PASSWORD: {get_param: MysqlRootPassword}
        NETWORK_MANAGER: nova
        NOVA_API_SERVICE_HOST: {get_param: NovaApiHost}
        NOVA_COMPUTE_SERVICE_HOST: {get_attr: [NovaCompute, networks, 0]}
        NOVA_CONDUCTOR_SERVICE_HOST: {get_param: NovaApiHost}
        NOVA_DB_NAME: nova
        NOVA_DB_PASSWORD: {get_param: NovaPassword}
        NOVA_DB_USER: nova
        NOVA_EC2_API_SERVICE_HOST: {get_attr: [NovaCompute, networks, ctlplane, 0]}
        NOVA_EC2_COMPUTE_SERVICE_HOST: {get_attr: [NovaCompute, networks, ctlplane, 0]}
        NOVA_EC2_NETWORK_SERVICE_HOST: {get_attr: [NovaCompute, networks, ctlplane, 0]}
        NOVA_EC2_SERVICE_HOST: {get_attr: [NovaCompute, networks, ctlplane, 0]}
        NOVA_KEYSTONE_PASSWORD: {get_param: NovaPassword}
        NOVA_KEYSTONE_USER: nova
        NOVA_NETWORK_SERVICE_HOST: {get_attr: [NovaCompute, networks, ctlplane, 0]}
        NOVA_VNCSERVER_PROXYCLIENT_ADDRESS: {get_attr: [NovaCompute, networks, ctlplane, 0]}
        NOVA_VNCSERVER_LISTEN_ADDRESS: {get_attr: [NovaCompute, networks, ctlplane, 0]}
        NOVA_NOVNC_PROXY_SERVICE_HOST: "0.0.0.0"
        NOVA_NOVNC_PROXY_PORT: 6080
        NOVA_NOVNC_BASE_ADDRESS: {get_attr: [NovaCompute, networks, ctlplane, 0]}
        PUBLIC_INTERFACE: br100
        PUBLIC_IP: {get_attr: [NovaCompute, networks, ctlplane, 0]}
        RABBITMQ_SERVICE_HOST: {get_param: RabbitHost}

  NovaComputeContainersInstall:
    type: OS::Heat::SoftwareDeployment
    depends_on: NovaComputeDeployment
    properties:
      config:
        get_resource: ConfigureNovaComputeContainers
      server:
        get_resource: NovaCompute

  ConfigureNovaComputeContainers:
    type: OS::Heat::StructuredConfig
    properties:
      group: docker-compose
      config:
        computedata:
          image: kollaglue/centos-rdo-nova-compute-data:kilo
          name: computedata

        libvirt:
          image: kollaglue/centos-rdo-nova-libvirt:kilo
          name: libvirt
          net: host
          pid: host
          privileged: true
          restart: always
          env_file:
           - /etc/openstack.env
          volumes:
           - /run:/run
           - /sys/fs/cgroup:/sys/fs/cgroup
          volumes_from:
           - computedata

        novanetwork:
          image: kollaglue/centos-rdo-nova-network:kilo
          name: nova-network
          net: host
          privileged: true
          restart: always
          env_file:
           - /etc/openstack.env
          volumes:
           - /run:/run
           - /sys/fs/cgroup:/sys/fs/cgroup
           - /lib/modules:/lib/modules:ro
          volumes_from:
           - computedata

        novacompute:
          image: kollaglue/centos-rdo-nova-compute:kilo
          name: nova-compute
          net: host
          privileged: true
          restart: always
          env_file:
           - /etc/openstack.env
          volumes:
           - /run:/run
           - /sys/fs/cgroup:/sys/fs/cgroup
           - /lib/modules:/lib/modules:ro
          volumes_from:
           - computedata
