heat_template_version: 2015-04-30

description: >
  A template which starts openstack on AtomicOS.

parameters:
  MariaBindAddress:
    type: string
    default: 127.0.0.1
  MariaRootPassword:
    type: string
    default: kolla
  RabbitServiceHost:
    type: string
    default: 127.0.0.1

resources:
  heat-docker-agents:
    type: DockerInc::Docker::Container
    properties:
      image: imain/heat-docker-agent:latest
      name: heat-docker-agent

  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }

  openstack_environment_deployment:
    type: OS::Heat::SoftwareDeployment
    depends_on: heat-docker-agents
    properties:
      config:
        get_resource: openstack_environment_setup
      input_values:
        BIND_ADDRESS: { get_param: MariaBindAddress }
        MARIADB_ROOT_PASSWORD: { get_param: MariaRootPassword }

  openstack_environment_setup:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
        - name: BIND_ADDRESS 
        - name: MARIADB_ROOT_PASSWORD
      config: |
        #!/bin/bash
        env > /etc/openstack.env

  UndercloudContainersInstall:
    type: OS::Heat::SoftwareDeployment
    depends_on: openstack_environment_setup
    properties:
      config:
        get_resource: Config_undercloud

  Config_undercloud:
    type: OS::Heat::StructuredConfig
    properties:
      group: docker-compose
      config:
        mariadbdata:
          image: kollaglue/centos-rdo-mariadb-data:latest
          name: mariadbdata

        mariadbapp:
          image: kollaglue/centos-rdo-mariadb-app:latest
          name: mariadbapp
          net: host
          restart: always
          env_file:
           - /etc/openstack.env
          volumes_from:
           - mariadbdata
