heat_template_version: 2014-10-16

parameters:
 image:
    type: string
    default: unused
 flavor:
    type: string
    default: unused
 key_name:
    type: string
    default: unused
 security_groups:
    type: json
    default: []
 # Require this so we can validate the parent passes the
 # correct value
 user_data_format:
    type: string
resources:
  # We just need something which returns a unique ID, but we can't
  # use RandomString because RefId returns the value, not the physical
  # resource ID, SoftwareConfig should work as it returns a UUID
  dummy:
    type: OS::Heat::SoftwareConfig
outputs:
  # FIXME(shardy) this is needed because TemplateResource returns an
  # ARN not a UUID, which overflows the Deployment server_id column..
  OS::stack_id:
    value: {get_resource: dummy}
